import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from '@/app/ui/footer'
import NavbarAcceuil from '@/app/ui/navbar-acceuil'
import NewQuizBtn from '@/app/ui/nouveau-quiz-btn'
import { createClient } from "@/lib/supabase/server"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  return (
    <html
      lang="fr"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex  flex-col">
        <NavbarAcceuil user={user }/>
        {children}
        <NewQuizBtn />
        <Footer />
      </body>
    </html>
  );
}
